name: "Master Build & Deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install
        run: |
          npm install
          npm run setheapsize

      - name: Production Build
        run: npx grunt prod --msg="Mirror set up by <a href='https://mmkf.au'>MMKF</a>"

      - name: Generate sitemap
        run: npx grunt exec:sitemap

      - name: Prepare for GitHub Pages
        run: npx grunt copy:ghPages

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: ./build/prod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
